### ISSUE TITLE
Rest API - Order by Create_Time

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-services#100]
- **Endpoint**
GET /api/organizations
GET /api/projects
GET /api/users

- **Requirement**
Resultset: ORDER BY ID DESC

**Comment by grakeshrao** [comment]
@Code4SocialGood  Should the latest created entity appear first?

**Comment by Code4SocialGood** [comment]
You are correct, I am wrong. Descending order.
Order by ID is enough, ID is system generated and is the same as create timestamp for order by

**Comment by Code4SocialGood** [comment]
Resolved with PR #126
