### ISSUE TITLE
RestAPI - Organization uploadLogo : No File upload option

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-services#12]
_From @arpitsrm on March 8, 2017 10:31_

Current functionality : 
![uploadlogo_1](https://cloud.githubusercontent.com/assets/6736845/23700148/fc100d82-0417-11e7-8d46-5528f0f9623b.png)

As per my understanding, It should be something like below : 
![upload_logo_expected](https://cloud.githubusercontent.com/assets/6736845/23700189/17503f5e-0418-11e7-9238-2a62da3bfc54.png)

Also, it can be a solution for #295 as well.

_Copied from original issue: Code4SocialGood/C4SG-Obsolete#482_

**Comment by Code4SocialGood** [comment]
_From @arpitsrm on March 8, 2017 20:3_

Submitted PR #484 
@Code4SocialGood As discussed, The alternate endPoint detail 
/api/organization/{organizationId}/uploadLogoAsFile

Let me know once it is tested on frontEnd so that I can make corresponding changes to Avartar and Resume as well.

**Comment by Code4SocialGood** [comment]
_From @arpitsrm on March 11, 2017 19:53_

@Code4SocialGood  :  Submitted PR #504

**Comment by arpitsrm** [comment]
Closing Issue. File Upload functionality done!
