### ISSUE TITLE
Rest API - User - Upload Resume

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-services#13]
_From @Code4SocialGood on March 7, 2017 23:10_

Requirement
Develop a new endpoint for UserController: POST /api/user/{userId}/uploadResume

Reference
POST /api/organization/{organizationId}/uploadLogo

_Copied from original issue: Code4SocialGood/C4SG-Obsolete#464_

**Comment by Code4SocialGood** [comment]
_From @arpitsrm on March 8, 2017 13:5_

Submitted PR. Please Review!

**Comment by Code4SocialGood** [comment]
_From @arpitsrm on March 11, 2017 19:53_

@Code4SocialGood  :  Submitted PR #504

**Comment by arpitsrm** [comment]
Closing issue.. Task Completed
