### ISSUE TITLE
Rest API - Organization - Search

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-services#187]
- **Endpoint**
GET /api/organizations/search

- **Requirement**
Refactor the endpoint:

Returns a list of organizations satisfy the search criteria:
1. has the keyword in organization name / description / state / country
2. has open opportunities
3. has status: A (active), D (deleted)
4. located in a list of countries
5. is category: N (for nonprofit), O (for open source), M (for misc)

All the search criteria is optional. If a search criteria is not provided, don't filter on it.

Sort the search result by organization name in ascending order.

**Comment by Code4SocialGood** [comment]
In this issue, you need to change two places in the code:

- **Endpoint definition in controller**
GET /api/organizations/search
It current accepts input parameters of: keyWord, country, open
Note: open opportunities means there is open projects from this organization. (select count(*) from project where organization = xx)
1. Please add input parameters of: 
status: accept value of 'A' or 'D', optional
category: accept value of "N', 'O', or 'M', optional
2. Please change "country" input parameter to accept a list of countries, not a single country

- **ProjectDAO**
Build the query.
Please note that all input parameters in the endpoint are optional. If no search criteria is provided, return all the organizations.

After the backend coding is done, please integrate test with frontend:
Click Organizations
Search on the left side search panel
1. This web page only returns active organizations. So the call to the endpoint should have status of 'A' 
2. There is no Country filter on frontend yet. So the call to the endpoint will not filter on country.

**Comment by joshisayali** [comment]
Will start working on it.
