### ISSUE TITLE
Organization List page: Filter by Category / Projects does not work

### ISSUE THREAD

**Issue by rituven** [Code4SocialGood/c4sg-services#226]
Navigate to the Organizations page from the C4SG home page.
 - 34 Organizations are listed.
Select a filter under 'Projects' (only 'Has Open Projects' is listed).
 - Can't select the filter. The button does not become 'checked' and the results do not change.
Select a filter option under 'Category'.
 - Results do not change regardless of whether I select one or all options. This might be an issue with the data (Can a project belong in multiple categories? If so, how is that stored?).

**Comment by Code4SocialGood** [comment]
Moved the issue to frontend: https://github.com/Code4SocialGood/c4sg-web/issues/352
