### ISSUE TITLE
Rest API - Slack Chat - Whether User Joined Slack Room

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-services#24]
- **Background**
C4SG web application will interface with Slack to provide chat room functionality.

- **Requirement**
Create Rest API end point: **isJoinedChat**
Description: This operation checks whether a user has joined the Slack team room
Input Parameter: user's email address
Constant: Slack team room: https://code4socialgood.slack.com/

- **Reference**
Slack API: https://api.slack.com/community
Slack tasks: https://github.com/Code4SocialGood/c4sg-services/issues/3, https://github.com/Code4SocialGood/c4sg-services/issues/24, https://github.com/Code4SocialGood/c4sg-services/issues/25, https://github.com/Code4SocialGood/c4sg-services/issues/26

- **Document**
[Vision - Online Chat.docx](https://github.com/Code4SocialGood/C4SG/files/812436/Vision.-.Online.Chat.docx)
[Use Case Specification - Online Chat.docx](https://github.com/Code4SocialGood/C4SG/files/812437/Use.Case.Specification.-.Online.Chat.docx)
[Chat Technical Design and Slack Integration.docx](https://github.com/Code4SocialGood/C4SG/files/812438/Chat.Technical.Design.and.Slack.Integration.docx)

**Comment by arpitsrm** [comment]
@Code4SocialGood : So this is what I had in mind : 
 Since there is no API to search user by email, we will have to follow the below steps : 
a. Get total usersList for our slack team using users.list webApi method
b. Then search if the particular email exists in the userlist

**Comment by Code4SocialGood** [comment]
1. Search the user table by email, check whether the user is registered in Slack  (add a flag column in the user table to indicate whether user joined Slack or not, column definition is not null with default 'N')
2. If flag is Y for the user, then the endpoint returns Y
3. If flag is N for the user, then 
a. Get total usersList for our slack team using users.list webApi method
b. Update the flag column in user table for the users in userList from Slack
c. Endpoint returns Y or N for the particular user requested

This logic caches the user list and saves us trip to Slack.
