### ISSUE TITLE
OrganizationController - Search - Accept Categories as a list

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-services#244]
1. Currently. the search() method accept single Category as String.
Please change to accept a list of categories. 
The input values are the codes for categories:
- N - Nonprofit
- O - Open source
- S - Social Enterprise
- U - Startup

2. If category is S or U, backend currently returns 500 error. Please fix this.

Please reference search() in ProjectController on how it accepts skills as list.

**Comment by kulgan** [comment]
Which controller has the search() method that needs to be worked on? I noticed there's a search feature in `UserController`, `ProjectController` and `OrganizationController` or is it for all of them?

**Comment by Code4SocialGood** [comment]
OrganizationController

**Comment by Code4SocialGood** [comment]
OrganizationController: Change the input parameter from String to Array[string]
![image](https://user-images.githubusercontent.com/24813620/27809620-f05ad28c-6016-11e7-8e81-cef63b6deda8.png)

To model ProjectController:
![image](https://user-images.githubusercontent.com/24813620/27809631-06194d7e-6017-11e7-99ec-545430a26a8d.png)

**Comment by Code4SocialGood** [comment]
Resolved in PR #266
