### ISSUE TITLE
Setup Logging Framework

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-services#259]
There is basically no logging implemented in the application. Please add Java logs using standard approach.
1. How to log: Setup Java logging framework
- In local environment (IDE), the logs are output to console. In server, the logs are output to log files.
- Prod will have INFO level for MVP release. It will be changed to ERROR level after the application becomes stable in prod.
2. What to log: The log should capture important events, input parameters, and system response. 

**Note**
1. In Heroku server, unlike a dedicate server, we are not able to view the log files. If the log setting is to output a log file, we will see nothing: no log file, no system output. To temporarily enable us to view the logs, please add a property flag to control whether the logs will be sent to console or file. We will temporarily set this flag to output to console even on Heroku server environment. 
2. We are investigating on the Heroku add-on for logging for a permanent solution,

**Comment by kulgan** [comment]
This work https://github.com/Code4SocialGood/c4sg-services/commit/a97aab01ccbaaacc4cce08d46efe436494efcac3 seems have covered setting up of logging, though they did not make use of spring boot provided logging capabilities? Is there any reason why these configs were removed?

**Comment by Code4SocialGood** [comment]
It might be removed when we realized the issue of logging on Heroku. When the app is deployed to heroku server, if the log is output to log file only, we are not able to access the log file. Maybe the config was removed so that the log is output to console instead of to log file.

Since we haven't studied on how to handle log file in a standard way in Heroku, at this time we have to dump to console. But at least we hope to use logging framework to control the log level, log format, etc.

**Comment by kulgan** [comment]
Ok, I am going to use Spring provided logging config, I think it works perfectly for this desired scenario

**Comment by Code4SocialGood** [comment]
Thanks!

**Comment by Code4SocialGood** [comment]
Resolved in PR #314
