### ISSUE TITLE
Create Project: Skills drop down not working

### ISSUE THREAD

**Issue by p-tal** [Code4SocialGood/c4sg-services#277]
Step to reproduce:
1.Login as nonprofit user: testnonprofituser2@gmail.com / Opensource5social!
2. Click from drop down : Create Project
3. Click on Select Skills.
4. The skills and NOT shown in drop down menu.
![new project skills](https://user-images.githubusercontent.com/29553195/28026296-9a2cf5a0-6563-11e7-9568-00303178a369.jpg)

**Comment by Code4SocialGood** [comment]
@p-tal The issue is resolved. Please retest.

**Comment by p-tal** [comment]
Skills drop down is showing. Retest successful. Defect is ok to close.
