### ISSUE TITLE
My Organization Page: Cosmetic Defect

### ISSUE THREAD

**Issue by p-tal** [Code4SocialGood/c4sg-services#278]
Steps to reproduce:
1.Login as nonprofit user: testnonprofituser2@gmail.com / Opensource5social!
2. Click from drop down: My organization

Cosmetic Defect shown below in screenshot:
![my organisation](https://user-images.githubusercontent.com/29553195/28033653-e9c5b444-657c-11e7-82bc-595286d24e14.jpg)

**Comment by Code4SocialGood** [comment]
Duplicate issue as #746 in frontend. Close this issue and keep the issue on frontend.
