### ISSUE TITLE
My Organization: organization Logo gets uploaded without saving

### ISSUE THREAD

**Issue by p-tal** [Code4SocialGood/c4sg-services#279]
.Login as nonprofit user: testnonprofituser2@gmail.com / Opensource5social!
2. Click from drop down: My organization
3. Upload organization logo.
4. The logo gets uploaded without SAVING
![upload logo](https://user-images.githubusercontent.com/29553195/28033726-2a572a56-657d-11e7-9eb2-e01410690819.jpg)

**Comment by Code4SocialGood** [comment]
The UPLOAD button saves the logo to the database for organization. This behaviors as designed.
Please retest.

**Comment by p-tal** [comment]
The Behavior is as designed. Defect OK to close.
