### ISSUE TITLE
My Settings: My Avatar picture gets uploaded without saving

### ISSUE THREAD

**Issue by p-tal** [Code4SocialGood/c4sg-services#280]
**Steps to Reproduce**
1.Login as nonprofit user: testnonprofituser2@gmail.com / Opensource5social!
2. Click from drop down: My Settings
3. Upload Picture in My Avatar
4. The logo gets uploaded without Saving.
![upload logo_my setting](https://user-images.githubusercontent.com/29553195/28034228-956cfb80-657e-11e7-8d44-ecd5438e73a9.jpg)

**Comment by Code4SocialGood** [comment]
The UPLOAD button saves the avatar to the database for user. This behaviors as designed.
Please retest.

**Comment by p-tal** [comment]
Functionality as designed. Defect OK to close
