### ISSUE TITLE
Create Project: Skills dropdown doesn't work

### ISSUE THREAD

**Issue by p-tal** [Code4SocialGood/c4sg-services#281]
Steps to Reproduce:
1.Login as nonprofit user: testnonprofituser2@gmail.com / Opensource5social!
2. Click from drop down: Create Project
3. click on Skills Drop down:

Expected Result: Skill list should be there and user should be able to select skills.
Actual Result: No skills are should. Screenshot attached
![new project skills](https://user-images.githubusercontent.com/29553195/28034579-980b492c-657f-11e7-9ec3-876c46a1eee6.jpg)

**Comment by Code4SocialGood** [comment]
The issue is resolved, please retest.

**Comment by p-tal** [comment]
The skills are shown in the dropdown. Retest successful. Defect is ok to close
