### ISSUE TITLE
Email Notification: Code for Social Good: You received an application

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-services#350]
Currently, the reply-to is: info@code4socialgood.org

Please change the reply-to to the applicant's email address. So that when the nonprofit receive the application email and click reply, the reply email will be sent to the applicant.

**Comment by felipealvesgnu** [comment]
Hey, I implemented the email feature, I can help on that !
@karthijey Did you start anything ? Otherwise I can check that.

**Comment by karthijey** [comment]
@Code4SocialGood Do we need to change the reply-to to organization's email address in the email we sent to the applicant also?

**Comment by karthijey** [comment]
I mean when the applicant is accepted for the project...

**Comment by Code4SocialGood** [comment]
Yes Please, thank you!

**Comment by karthijey** [comment]
@felipealves-gnu yes I am working on issue #349 and #350

**Comment by felipealvesgnu** [comment]
@karthijey So I will just review when you push the code !!

**Comment by karthijey** [comment]
@felipealves-gnu Okay thanks.
