### ISSUE TITLE
Remove Slack username in emails sent out

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-services#358]
**1. Code for Social Good: Your application is submitted** 
- Remove slack username line
- Phone number shouldn't be a link, it should be a plain text

![image](https://user-images.githubusercontent.com/24813620/30517432-9cf57e5a-9b24-11e7-9260-bc7121bf905c.png)

**2. Code for Social Good: You received an application**
- Remove slack username line

![image](https://user-images.githubusercontent.com/24813620/30517454-30fe3b1e-9b25-11e7-9947-3a17f0751616.png)

**3. Code for Social Good: Your application is accepted**
- Remove slack username line
- Phone number shouldn't be a link, it should be a plain text

![image](https://user-images.githubusercontent.com/24813620/30517542-8f5ba824-9b28-11e7-9f10-ec6b42ea419f.png)

**4. Code for Social Good: Your application is declined**
- Remove slack username line
- Phone number shouldn't be a link, it should be a plain text

**Comment by professionalsql** [comment]
This is a partial duplicate/overlap.
The slack line was changed such that it stays visible, but does not include any link at all if the user does not have a slack name configured. This was done as part of issue #1545 in the web branch. The phone link was not checked or dealt with at that time (I had not seen this issue as yet).

QUESTION: I haven't testing a config that has a phone # set. What mime-type is being associated with the phone number? It seems very plausible that it *should* be a link to enable autodialers.

**Comment by Code4SocialGood** [comment]
@professionalsql Plain text should be fine. At this time our email are basically plain text (although with HTML template)

**Comment by Code4SocialGood** [comment]
Close this issue, move to frontend
