### ISSUE TITLE
Delete User - Change email address

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-services#363]
When a user is deleted, we perform "soft delete", which means we keep the physical database record, but change the user status to 'D'. We also change the user email address by appending -deleted, so that this email address could be reused if use register later again. 

1. When user is deleted, email address is appended with -deleted. This works fine.
2. User is registered again with the same email address. 
3. User click delete. System try to append -delete to the email address, this throw an exception since the email with -delete already exist. 

Fix: When user is deleted, append -deleted to email address. If email with -deleted already exist, append with -deleted-deleted, etc.

**Comment by HolSeL** [comment]
2. When the user registers again, you can delete "-delete" in email address. Therefore, the repeated deletion will work correctly.
Since the addition of a -delete-delete is not entirely correct

**Comment by trishulpani** [comment]
I agree with @harshareddy75. 
My 2 cents:
- appending ‘-deleted’ indefinitely is not a good idea as mentioned above. 
- user status should indicate whether the user is active or not. It sounds more clean. It will also help if inactive user data needs to be archived in the future. Easier for queries as well.

**Comment by linkin-park** [comment]
@Code4SocialGood 
its better to have a bit column called status  where values are 0 or 1.
where 0 for member , 1 for non-member.
