### ISSUE TITLE
Rest API - Home Controller - Remove

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-services#51]
Do we need HomeController and operations in it?
- If no, remove it.
- If yes, explain why.

HomeController:
DELETE /home
GET /home
HEAD /home
OPTIONS /home
PATCH /home
POST /home
PUT /home

**Comment by gauravhp** [comment]
I checked the code, we do not need home controller and can remove it.

I will make the changes are submit merge request

**Comment by gauravhp** [comment]
Just to update I submitted, and its be pending approval
