### ISSUE TITLE
Rest API - Organization - Search By Keyword

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-services#62]
- **Rest API**
GET /api/organizations/search (already exist)

- **Requirement**
1. In organization table, add a column: project_updated_time, timestamp, not null

2. Searches the keyword in organization name and description, case insensitive. 

3. The search result is sorted by project update time in descending order. Sorting by project update timestamp ranks the most active organizations on top of research result.

4. Add the following comments to the endpoint operation (serve as Javadoc):
_`Searches the keyword in organization name and description, case insensitive. The search result is sorted by project update time in descending order.`_

**Comment by gauravhp** [comment]
Made code change and submitted Pull request for review.

**Comment by Code4SocialGood** [comment]
Closed with PR.
