### ISSUE TITLE
Rest API - Project - Add Project - Dependent on #62

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-services#63]
Endpoint: POST /api/projects/add

Requirement: Update "project update time" column in organization table

Note: "project update time" column will be created in issue #62

**Comment by gauravhp** [comment]
Raised a Pull request

**Comment by gauravhp** [comment]
https://github.com/Code4SocialGood/c4sg-services/pull/114

**Comment by Code4SocialGood** [comment]
Resolved with PR
