### ISSUE TITLE
Rest API - Project/User/Organization - Create Timestamp

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-services#75]
- **End Points**
POST /api/projects/add
POST /api/organization/create
POST /api/users

- Requirement
1. The tables have created_time column. This column has no default value. When a new record is inserted, explicitly set the value of created_at column to be null. 
Sample statement: insert into project (name, description, **created_time**) values ('project test', 'project test', **null**) 
2. Renaming the 3 endpoints to follow the same naming standard.

**Comment by Code4SocialGood** [comment]
@felipealves-gnu 
The following 3 operations should be refacored to following the same naming standard. What should be the endpoint format for adding an entity?
POST /api/projects/add
POST /api/organization/create
POST /api/users

**Comment by felipealvesgnu** [comment]
I´m refactoring those endpoints to become:
```
POST /api/projects
POST /api/organizations
POST /api/users
```

**Comment by gauravhp** [comment]
@felipealves-gnu I am not sure if you are working on this entire issue or only #2 

Please let me know

**Comment by felipealvesgnu** [comment]
No, @gauravhp I'm working on this #84

**Comment by gauravhp** [comment]
okay @felipealves-gnu , I will take care of both the requirements in this issue then.

**Comment by gauravhp** [comment]
Made the change and submitted a merge request for No 1

For No 2, the APIs are already

> POST /api/projects
> POST /api/organizations
> POST /api/users

So no change needed
