### ISSUE TITLE
Exception Handling

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-services#8]
_From @shobhit-sri on January 15, 2017 23:30_

1. Create custom run time exception classes to handle exceptions.
2. Map exceptions to response status codes (Bad Request, Not Found)

_Copied from original issue: Code4SocialGood/C4SG#113_

**Comment by grakeshrao** [comment]
Question:

As the BadRequest, NotFound, UserProjectException are already there in Exceptions folder, I assume this task is to add the error handlers in GenericController.java and extend all the controllers from GenericController.java.  

 Please correct me if I am wrong.

Regards,
Rakesh

**Comment by Code4SocialGood** [comment]
There is no specific requirement on this task. Please take a look at each layer, i.e., Controller, Service, DTO, DAO, Entity...and setup a standard way for application to throw and handle the exceptions.

**Comment by Code4SocialGood** [comment]
1. Please reference the following links on handling exceptions in Spring framework:
https://spring.io/blog/2013/11/01/exception-handling-in-spring-mvc
http://www.journaldev.com/2651/spring-mvc-exception-handling-controlleradvice-exceptionhandler-handlerexceptionresolver
http://www.baeldung.com/exception-handling-for-rest-with-spring

2. Refactor our backend application to handle the exceptions in a consistent way in each class.

**Comment by grakeshrao** [comment]
I created The pull request for this task. Also changed the assigne to Code4SocialGood as per the document.

**Comment by Code4SocialGood** [comment]
Resolved with PR
