### ISSUE TITLE
Implement Travis CI

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-services#9]
_From @Code4SocialGood on December 29, 2016 23:12_

Implement Travis CI to run tests on both the server, client, and end to end.

_Copied from original issue: Code4SocialGood/C4SG#26_

**Comment by felipealvesgnu** [comment]
@russon77 can you check the implementation for c4sg-web ?

**Comment by tristanmkernan** [comment]
https://github.com/Code4SocialGood/c4sg-web/blob/master/.travis.yml

@felipealves-gnu what do you mean?

**Comment by felipealvesgnu** [comment]
@russon77 sorry, I didn't see. Thanks
