### ISSUE TITLE
Rest API - User - Create User - Refactor

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/c4sg-services#93]
- **Endpoint**
POST /api/users

- **Requirement**
1. Create a new DTO: CreateUserDTO, with fields as below:
  username 
  firstName 
  lastName 
  email: Required
  phone 
  city 
  state 
  country 
  zip 
  title
  introduction 
  linkedinUrl
  personalUrl 
  githubUrl
  avatarUrl
  resumeUrl
  role 
  publicProfileFlag 
  chatFlag 
  forumFlag 

2. Change the input parameter from UserDTO to CreateUserDTO

- **Note on Frontend testing**
Test User Signup from frontend to see whether frontend change is needed to call this refactored endpoint.

**Comment by grakeshrao** [comment]
By changing UserDTO to CreateUserDTO, The updateUser(PUT) arguements will also be changed right?

**Comment by Code4SocialGood** [comment]
It depends. 

For example, when user is created, we don't need to assign user status - status is ACTIVE by default. But when we update user, we could update user status.

We will think about how updateUser should be designed.
